"""Add Field model and update Candidate

Revision ID: d8a14cf5b037
Revises: 68a57480ecda
Create Date: 2026-05-11 15:18:52.599097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8a14cf5b037'
down_revision: Union[str, None] = '68a57480ecda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_fields_id'), 'fields', ['id'], unique=False)
    op.add_column('candidates', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('candidates', sa.Column('field_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'candidates', 'fields', ['field_id'], ['id'])
    op.drop_column('candidates', 'position')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('position', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_column('candidates', 'field_id')
    op.drop_column('candidates', 'phone_number')
    op.drop_index(op.f('ix_fields_id'), table_name='fields')
    op.drop_table('fields')
    # ### end Alembic commands ###
